"""Add discord fields to channel

Revision ID: 3ab91f4770b8
Revises: d9f8775993b0
Create Date: 2026-07-11 22:59:39.324134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab91f4770b8'
down_revision: Union[str, Sequence[str], None] = 'd9f8775993b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('discord_status', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('discord_type', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('discord_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'discord_source')
    op.drop_column('channels', 'discord_type')
    op.drop_column('channels', 'discord_status')
    # ### end Alembic commands ###
