"""Add Phase 1B models and fields

Revision ID: c3befe61dc03
Revises: a4d9a3a755fb
Create Date: 2026-07-09 23:14:57.588945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3befe61dc03'
down_revision: Union[str, Sequence[str], None] = 'a4d9a3a755fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_quota_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('daily_quota_consumed', sa.Integer(), nullable=True),
    sa.Column('remaining_quota_estimate', sa.Integer(), nullable=True),
    sa.Column('requests_made', sa.Integer(), nullable=True),
    sa.Column('failed_requests', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('search_timestamp', sa.DateTime(), nullable=False),
    sa.Column('returned_video_ids', sa.Text(), nullable=True),
    sa.Column('returned_channel_ids', sa.Text(), nullable=True),
    sa.Column('next_page_token', sa.String(), nullable=True),
    sa.Column('api_response_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('channels', sa.Column('is_german', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('is_trading', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('has_recent_uploads', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('has_community_links', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('needs_manual_review', sa.Boolean(), nullable=True))
    op.add_column('channels', sa.Column('last_seen', sa.DateTime(), nullable=False))
    op.add_column('channels', sa.Column('language_confidence', sa.Float(), nullable=True))
    op.add_column('crawl_jobs', sa.Column('channel_id', sa.String(), nullable=True))
    op.add_column('crawl_jobs', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('crawl_jobs', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('crawl_jobs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('crawl_jobs', sa.Column('created_time', sa.DateTime(), nullable=False))
    op.add_column('videos', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('language_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'language_confidence')
    op.drop_column('videos', 'thumbnail_url')
    op.drop_column('crawl_jobs', 'created_time')
    op.drop_column('crawl_jobs', 'retry_count')
    op.drop_column('crawl_jobs', 'reason')
    op.drop_column('crawl_jobs', 'priority')
    op.drop_column('crawl_jobs', 'channel_id')
    op.drop_column('channels', 'language_confidence')
    op.drop_column('channels', 'last_seen')
    op.drop_column('channels', 'needs_manual_review')
    op.drop_column('channels', 'has_community_links')
    op.drop_column('channels', 'has_recent_uploads')
    op.drop_column('channels', 'is_trading')
    op.drop_column('channels', 'is_german')
    op.drop_table('community_links')
    op.drop_table('search_results')
    op.drop_table('api_quota_logs')
    # ### end Alembic commands ###
