"""add_phase_1c_models_and_fields

Revision ID: d9f8775993b0
Revises: c3befe61dc03
Create Date: 2026-07-10 02:23:28.937755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f8775993b0'
down_revision: Union[str, Sequence[str], None] = 'c3befe61dc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrase_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phrase_a', sa.String(), nullable=False),
    sa.Column('phrase_b', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phrase_a'], ['phrases.phrase'], ),
    sa.ForeignKeyConstraint(['phrase_b'], ['phrases.phrase'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phrase', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phrase'], ['phrases.phrase'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('channels', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('phrases', sa.Column('average_recency', sa.Float(), nullable=True))
    op.add_column('phrases', sa.Column('average_subscribers', sa.Float(), nullable=True))
    op.add_column('queries', sa.Column('parent_phrase', sa.String(), nullable=True))
    op.add_column('queries', sa.Column('generation_time', sa.DateTime(), nullable=True))
    op.add_column('queries', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('queries', sa.Column('new_channels_discovered', sa.Integer(), nullable=True))
    op.add_column('queries', sa.Column('new_videos_discovered', sa.Integer(), nullable=True))
    op.add_column('queries', sa.Column('duplicate_rate', sa.Float(), nullable=True))
    op.add_column('queries', sa.Column('new_phrases_discovered', sa.Integer(), nullable=True))
    op.add_column('queries', sa.Column('cost_per_new_channel', sa.Float(), nullable=True))
    op.add_column('queries', sa.Column('priority_modifier', sa.Float(), nullable=True))
    op.add_column('video_phrases', sa.Column('channel_id', sa.String(), nullable=True))
    op.add_column('video_phrases', sa.Column('source', sa.String(), nullable=True))
    op.add_column('video_phrases', sa.Column('first_seen', sa.DateTime(), nullable=False))
    op.add_column('video_phrases', sa.Column('last_seen', sa.DateTime(), nullable=False))
    op.add_column('videos', sa.Column('transcript_attempted', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'topic')
    op.drop_column('videos', 'transcript_attempted')
    op.drop_column('video_phrases', 'last_seen')
    op.drop_column('video_phrases', 'first_seen')
    op.drop_column('video_phrases', 'source')
    op.drop_column('video_phrases', 'channel_id')
    op.drop_column('queries', 'priority_modifier')
    op.drop_column('queries', 'cost_per_new_channel')
    op.drop_column('queries', 'new_phrases_discovered')
    op.drop_column('queries', 'duplicate_rate')
    op.drop_column('queries', 'new_videos_discovered')
    op.drop_column('queries', 'new_channels_discovered')
    op.drop_column('queries', 'confidence_score')
    op.drop_column('queries', 'generation_time')
    op.drop_column('queries', 'parent_phrase')
    op.drop_column('phrases', 'average_subscribers')
    op.drop_column('phrases', 'average_recency')
    op.drop_column('channels', 'topic')
    op.drop_table('phrase_scores')
    op.drop_table('phrase_relationships')
    # ### end Alembic commands ###
